"""crear estructura inicial

Revision ID: d94d494e9675
Revises: 
Create Date: 2026-06-29 13:38:56.027011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94d494e9675'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('participantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('tipo_participante', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_participantes_id'), 'participantes', ['id'], unique=False)
    op.create_table('relaciones_comerciales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_relaciones_comerciales_id'), 'relaciones_comerciales', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=100), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuit')
    )
    op.create_table('participante_relacion_comercial',
    sa.Column('participante_id', sa.Integer(), nullable=False),
    sa.Column('relacion_comercial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.ForeignKeyConstraint(['relacion_comercial_id'], ['relaciones_comerciales.id'], ),
    sa.PrimaryKeyConstraint('participante_id', 'relacion_comercial_id')
    )
    op.create_table('personas_fisicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('precio_minorista', sa.Float(), nullable=False),
    sa.Column('precio_mayorista', sa.Float(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_reservado', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('contrasenia', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('participante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participante_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participante_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.String(length=20), nullable=False),
    sa.Column('fecha_ingreso', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['personas_fisicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legajo')
    )
    op.create_table('movimientos_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', 'RESERVA', 'LIBERACION', 'AJUSTE', name='tipomovimientostock'), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_stock_id'), 'movimientos_stock', ['id'], unique=False)
    op.create_table('producto_proveedor',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['participantes.id'], ),
    sa.PrimaryKeyConstraint('producto_id', 'proveedor_id')
    )
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'CANCELADO', 'ENTREGADO', name='estadopedido'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('repartidor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['participantes.id'], ),
    sa.ForeignKeyConstraint(['repartidor_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('detalles_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('tipo_precio', sa.String(length=50), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_pedido_id'), 'detalles_pedido', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'RECHAZADO', 'ANULADO', name='estadopago'), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('tipo_pago', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_table('pagos_efectivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto_recibido', sa.Float(), nullable=False),
    sa.Column('vuelto', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_mercado_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preference_id', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('external_reference', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_transferencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cbu', sa.String(length=22), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('comprobante_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pagos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos_transferencia')
    op.drop_table('pagos_mercado_pago')
    op.drop_table('pagos_efectivo')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_detalles_pedido_id'), table_name='detalles_pedido')
    op.drop_table('detalles_pedido')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_table('usuario_rol')
    op.drop_table('producto_proveedor')
    op.drop_index(op.f('ix_movimientos_stock_id'), table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_table('empleados')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_table('personas_fisicas')
    op.drop_table('participante_relacion_comercial')
    op.drop_table('empresas')
    op.drop_table('roles')
    op.drop_index(op.f('ix_relaciones_comerciales_id'), table_name='relaciones_comerciales')
    op.drop_table('relaciones_comerciales')
    op.drop_index(op.f('ix_participantes_id'), table_name='participantes')
    op.drop_table('participantes')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
